package gr.uom.java.xmi.diff;

public enum MotivationType {
	EM_REUSABLE_METHOD,
	EM_INTRODUCE_ALTERNATIVE_SIGNATURE,
	EM_DECOMPOSE_TO_IMPROVE_READABILITY,
	EM_FACILITATE_EXTENSION,
	EM_REMOVE_DUPLICATION,
	EM_REPLACE_METHOD_PRESERVING_BACKWARD_COMPATIBILITY,
	EM_IMPROVE_TESTABILITY,
	EM_ENABLE_OVERRIDING,
	EM_ENABLE_RECURSION,
	EM_INTRODUCE_FACTORY_METHOD,
	EM_INTRODUCE_ASYNC_OPERATION,
	
	MC_MOVE_CLASS_TO_APPROPRIATE_CONTAINER,
	MC_INTRODUCE_SUB_PACKAGE,
	MC_CONVERT_TO_TOP_LEVEL_CONTAINER,
	MC_REMOVE_INNER_CLASS_FROM_DEPRECATED_CONTAINER,
	MC_REMOVE_FROM_PUBLIC_API,
	MC_CONVERT_TO_INEER_CLASS,
	MC_ELIMINATE_DEPENDENCIES,
	MC_ELIMINATE_REDUNDANT_SUB_PACKAGE,
	MC_BACKWARD_COMPATIBILITY,
	
	MA_MOVE_ATTRIBUTE_TO_APPROPRIATE_CLASS,
	MA_REMOVE_DUPLICATION,
	
	RP_IMPROVE_PACKAGE_NAME,
	RP_ENFORCE_NAMING_CONSISTENCY,
	RP_MOVE_PACKAGE_TO_APPROPRIATE_CONTAINER,
	
	MM_MOVE_METHOD_TO_APPROPRIATE_CLASS,
	MM_MOVE_METHOD_TO_ENABLE_REUSE,
	MM_ELIMINATE_DEPENDENCIES,
	MM_REMOVE_DUPLICATION,
	MM_ENABLE_OVERRIDING,
	
	IM_ELIMINATE_UNNECESSARY_METHOD,
	IM_CALLER_BECOMES_TRIVIAL,
	IM_IMPROVE_READABILITY,
	
	ES_EXTRACT_COMMON_STATE_OR_BEHAVIOUR,
	ES_ELIMINATE_DEPENDENCIES,
	ES_DECOMPOSE_CLASS,
	
	PUM_MOVE_UP_COMMON_METHODS,
	
	PUA_MOVE_UP_COMMON_ATTRIBUTES,
	
	EI_FACILITATE_EXTENSION,
	EI_ENABLE_DEPENDENCY_INJECTION,
	EI_ELIMINATE_DEPENDENCIES,
	
	PDA_SPECIALIZED_IMPLEMENTATION,
	PDA_ELIMINATE_DEPENDENCIES,
	
	PDM_SPECIALIZED_IMPLEMENTATION
	
}
