package gr.uom.java.xmi.diff;

public enum MotivationType {
	EM_REUSABLE_METHOD,
	EM_INTRODUCE_ALTERNATIVE_SIGNATURE,
	EM_DECOMPOSE_TO_IMPROVE_READABILITY,
	EM_FACILITATE_EXTENSION,
	EM_REMOVE_DUPLICATION,
	EM_REPLACE_METHOD_PRESERVING_BACKWARD_COMPATIBILITY,
	EM_IMPROVE_TESTABILITY,
	EM_ENABLE_OVERRIDING,
	EM_ENABLE_RECURSION,
	EM_INTRODUCE_FACTORY_METHOD,
	EM_INTRODUCE_ASYNC_OPERATION;
	
}
